name: Run Script

on: push

jobs:
  apply:
    name: Apply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run myscript Script
        run: sh ./myscript.sh
        shell: bash
        env: # see Production-AssetCDN-GitHubActionsYearbookFiles user on IAM
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
